// Main barrel export for @leadflow/db
export { db, default } from "./client";

// Re-export all Prisma types for convenience
export type {
  Organization,
  Workspace,
  User,
  TeamMember,
  Session,
  ApiKey,
  AuditLog,
  Subscription,
  UsageRecord,
  Invoice,
  Lead,
  Contact,
  LeadScore,
  LeadActivity,
  WebsiteAudit,
  Pipeline,
  Deal,
  Task,
  Meeting,
  Note,
  Attachment,
  Proposal,
  Campaign,
  Sequence,
  SequenceStep,
  CampaignLead,
  SequenceEnrollment,
  EmailEvent,
  Workflow,
  WorkflowRun,
  AgentRun,
  PromptRecord,
  KnowledgeDocument,
  KnowledgeChunk,
  EvalCase,
  EvalResult,
  Notification,
  Prisma,
} from "@prisma/client";

export {
  UserRole,
  SubscriptionPlan,
  SubscriptionStatus,
  LeadStatus,
  LeadSource,
  DealStage,
  TaskStatus,
  CampaignStatus,
  CampaignChannel,
  SequenceStatus,
  EmailEventType,
  WorkflowStatus,
  WorkflowRunStatus,
  AgentRunStatus,
  NotificationType,
  SyncStatus,
} from "@prisma/client";
