import { BaseMessage } from "@langchain/core/messages";

export interface AgentState {
  /**
   * The conversation history and intermediate steps.
   */
  messages: BaseMessage[];

  /**
   * The current goal or overall request.
   */
  goal: string;

  /**
   * The execution plan generated by the planner agent.
   */
  plan: string[];

  /**
   * The current active step in the plan.
   */
  currentStepIndex: number;

  /**
   * The next agent to route to, determined by the supervisor.
   */
  next: string;

  /**
   * Any context or data gathered by agents (e.g., leads discovered).
   */
  context: Record<string, any>;
}

export const agentStateChannels = {
  messages: {
    value: (x: BaseMessage[], y: BaseMessage[]) => x.concat(y),
    default: () => [],
  },
  goal: {
    value: (x: string, y: string) => y ?? x,
    default: () => "",
  },
  plan: {
    value: (x: string[], y: string[]) => y ?? x,
    default: () => [],
  },
  currentStepIndex: {
    value: (x: number, y: number) => y ?? x,
    default: () => 0,
  },
  next: {
    value: (x: string, y: string) => y ?? x,
    default: () => "FINISH",
  },
  context: {
    value: (x: Record<string, any>, y: Record<string, any>) => ({ ...x, ...y }),
    default: () => ({}),
  },
};
